name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

      - name: Run type check
        run: npm run typecheck

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Check build
        run: npm run build

      - name: Comment PR with test results
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const fs = require('fs');
            let comment = '## 🔍 PR Validation Results\n\n';

            // Add status based on job result
            if ('${{ job.status }}' === 'success') {
              comment += '✅ All checks passed!\n\n';
            } else {
              comment += '❌ Some checks failed. Please review the logs.\n\n';
            }

            comment += '### Checks performed:\n';
            comment += '- Code formatting\n';
            comment += '- ESLint validation\n';
            comment += '- TypeScript compilation\n';
            comment += '- Unit tests with coverage\n';
            comment += '- Build verification\n';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
